version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=usr
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'
